### ISSUE TITLE
webpack-seed-master运行错误

### ISSUE THREAD

**Issue by hrh94** [Array-Huang/webpack-seed#12]
运行npm install --global webpack webpack-dev-server webpack-bundle-analyzer和npm install
后运行npm run build报错：
```
> webpack-seed@1.2.2 build R:\frontProjects\webpackbin\webpack-seed-master
> node npm-scripts/before-build.script.js && webpack --progress --colors --bail

build目录已清空
module.js:471
    throw err;
    ^

Error: Cannot find module 'webpack-bundle-analyzer'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (R:\frontProjects\webpackbin\webpack-seed-master\webpack-config\inherit\plugins.config.js:4:62)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (R:\frontProjects\webpackbin\webpack-seed-master\webpack-config\plugins.product.config.js:2:21)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\11311\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! webpack-seed@1.2.2 build: `node npm-scripts/before-build.script.js && webpack --progress --colors --bail`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webpack-seed@1.2.2 build script 'node npm-scripts/before-build.script.js && webpack --progress --colors --bail'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the webpack-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node npm-scripts/before-build.script.js && webpack --progress --colors --bail
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs webpack-seed
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls webpack-seed
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     R:\frontProjects\webpackbin\webpack-seed-master\npm-debug.log

```

就我个人理解应该是本地没安装webpack-bundle-analyzer导致，于是运行 npm install webpack-bundle-analyzer命令，接着再次打包npm run build，没有出现错误，运行webpack-seed-master\src\index.html文件，提示 Cannot GET /src/index/index/page.html

**Comment by Array-Huang** [comment]
的确是需要全局安装`webpack-bundle-analyzer`

```
npm i -global webpack-bundle-analyzer
```

**Comment by Array-Huang** [comment]
另外，你是怎么

> 运行webpack-seed-master\src\index.html文件

的？
