### ISSUE TITLE
npm run start出错

### ISSUE THREAD

**Issue by rotate720deg** [Array-Huang/webpack-seed#15]
```
D:\nodejs\node_modules\node_global\webpack-bundle-analyzer:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
```

nodejs：v4.4.6
npm: 2.15.5

**Comment by Array-Huang** [comment]
未能重现你的这个问题，不过我改了一下利用webpack-bundle-analyzer的方式，应该不会再出这问题了。

[传送门](https://github.com/Array-Huang/webpack-seed/tree/v1.3.1)
