### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by cqgsm** [Array-Huang/webpack-seed#8]
TypeError: Cannot read property 'name' of undefined                                                                                                                                 
    at Tapable.Compilation.addModuleDependencies (C:\Users\Administrator\AppData\Roaming\npm\node_modules\webpack\lib\Compilation.js:174:108)                                       
    at Tapable.Compilation.processModuleDependencies (C:\Users\Administrator\AppData\Roaming\npm\node_modules\webpack\lib\Compilation.js:164:7)                                     
    at Tapable.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\webpack\lib\Compilation.js:312:11)                                                              
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\webpack\lib\Compilation.js:119:4                                                                                     
    at Array.forEach (native)                                                                                                                                                       
    at callback (C:\Users\Administrator\AppData\Roaming\npm\node_modules\webpack\lib\Compilation.js:118:12)                                                                         
    at Tapable.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\webpack\lib\Compilation.js:136:10)                                                              
    at DependenciesBlock.DelegatedModule.build (C:\Users\Administrator\Desktop\webpack-seed-master\webpack-seed-master\node_modules\webpack\lib\DelegatedModule.js:41:2)            
    at Tapable.Compilation.buildModule (C:\Users\Administrator\AppData\Roaming\npm\node_modules\webpack\lib\Compilation.js:122:9)                                                   
    at Tapable.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\webpack\lib\Compilation.js:301:9)                                                               
    at Tapable.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\webpack\lib\NormalModuleFactory.js:57:13)                                                       
    at Tapable.applyPluginsAsyncWaterfall (C:\Users\Administrator\AppData\Roaming\npm\node_modules\webpack\node_modules\tapable\lib\Tapable.js:75:69)                               
    at Tapable.onDoneResolving (C:\Users\Administrator\AppData\Roaming\npm\node_modules\webpack\lib\NormalModuleFactory.js:37:10)                                                   
    at Tapable.onDoneResolving (C:\Users\Administrator\AppData\Roaming\npm\node_modules\webpack\lib\NormalModuleFactory.js:118:6)                                                   
    at Tapable.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\webpack\lib\NormalModuleFactory.js:96:29)                                                       
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\webpack\node_modules\async\lib\async.js:251:17

能build 成功，npm run start 报这个错

**Comment by Array-Huang** [comment]
我刚刚试了一下clone整个库下来然后按我README里的教程跑了一下，发现缺了局部安装的webpack会导致好几个webpack的plugin装不上，所以我现在把webpack又添到package.json，然后这下子就没问题了。

不过，我之前那是连build都build不了的，所以不太明白为什么你可以build但却不能start。

或者你再clone一个然后按我README说的试试？

**Comment by cqgsm** [comment]
刚开始各种报错，我查了下，安装了局部的webpack。非常感谢，我试试

**Comment by Array-Huang** [comment]
好的，有问题欢迎再过来提哈
